version: "3"
services:

  hapi-fhir-jpa:
    image: arkhn/hapi-fhir-jpa:latest
    build: .
    restart: on-failure
    volumes:
      - ./application.override.yml:/opt/hapi/application.yaml
    ports:
      - 8080:8080
    environment:
      SPRING_CONFIG_LOCATION: file:///opt/hapi/application.yaml
      HAPI_FHIR_URL: http://localhost:8080/fhir
      JDK_JAVA_OPTIONS: -Xmx4g
    depends_on:
      - elasticsearch
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=deadbeefdeadbeef
      - POSTGRES_DB=test-hapi-db
    ports:
      - 5432:5432
    volumes:
      - hapi-pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:6.8.13
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=SomePassword
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - hapi-eldata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.13
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=SomePassword
    depends_on:
      - elasticsearch

volumes:
  hapi-pgdata:
  hapi-eldata:
